<?php

/**
 * @file
 * Provides custom functionality related to the faculty role.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter() node_form.
 */
function gsb_faculty_role_form_node_form_alter(&$form, $form_state) {
  $form['#process'][] = 'gsb_faculty_role_node_form_process';
}

/**
 * #process callback: Hide elements on the node form.
 */
function gsb_faculty_role_node_form_process($form) {
  if (!user_access('administer nodes')) {
    // Hide the vertical tabs at the bottom of the form.
    $form['additional_settings']['#access'] = FALSE;
    // Hide all elements inside that vertical tab.
    foreach (element_children($form) as $key) {
      if (isset($form[$key]['#group']) && $form[$key]['#group'] == 'additional_settings') {
        $form[$key]['#access'] = FALSE;
      }
    }
  }

  if (in_array('Faculty', $GLOBALS['user']->roles)) {
    // Hide all buttons except the 'Publish' button.
    foreach (element_children($form['actions']) as $key) {
      if ($key != 'save_and_publish') {
        $form['actions'][$key]['#access'] = FALSE;
      }
    }
  }
  return $form;
}
